# Generated by Django 2.2.28 on 2022-05-04 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(help_text='Название ингредиента', max_length=200, verbose_name='Название ингредиента'),
        ),
    ]
